### ISSUE TITLE
Tables ownership

### ISSUE THREAD

**Issue by thamerlan** [enova/pgl_ddl_deploy#23]
Hi,
I want to understand deeper the meaning of the 'app_owner' role. As I understand it should be an owner of all replicated tables on the subscriber?
For us this is not an options, since we have multiple schema with its own owners (one schema = 1 owner with the same name). What can we do? Can we grant some permissions to the 'app_owner' to work with other owner's schema/tables?

**Comment by jfinzel** [comment]
It is not a requirement that the app_owner role owns all of the tables on the subscriber.

Any DDL executed on your provider system will execute as the exact same role on the subscriber system. That means that on the subscriber system that role has to exist and have permissions to modify or create new tables on the subscriber side. 

So the way we handle this in our environment is that there is always a migration role that runs any DDL on our application databases. We create the same role as a NOLOGIN role on the subscriber side and it has ownership over only of those schemas from that particular source system. Also for what it’s worth we have an event trigger in place to automatically assign permission for newly created schemas by application migration roles.

So what you will see for example in one of our shared systems with many different providers is that there are a handful of no login application roles that simply own each particular schema for the respective applications.  When a migration comes through that same DDL executes on the subscriber side and as that role has sufficient permissions to modify any tables involved. 

Does that make sense?

**Comment by thamerlan** [comment]
Great. Thanks. This is exactly what I need.

**Comment by jfinzel** [comment]
If you have time, a PR to clarify the docs on this  from your perspective would be appreciated!
