### ISSUE TITLE
DDL for partitioned tables

### ISSUE THREAD

**Issue by thamerlan** [enova/pgl_ddl_deploy#24]
Hi,
Will "pgl_ddl_deploy" work with partitioned tables? 
Will it replicate DDL for the new inherited partition to the subscriber?

--
Thanks, 
Timur

**Comment by jfinzel** [comment]
@thamerlan the only reason it should not work is if the syntax isn't supported on the subscriber, obviously, like if you replicated from 10 to 9.6 and tried to use the new partition syntax.

Whatever SQL you execute on the provider will be executed on the subscriber at the same transactional moment, so long as you have configured it for the tables of interest.

**Comment by jfinzel** [comment]
I trust this answers the question - please re-open if you have any issue.
