### ISSUE TITLE
pglogical for PG12 is ready

### ISSUE THREAD

**Issue by df7cb** [enova/pgl_ddl_deploy#52]
Time for a new release?

**Comment by df7cb** [comment]
Fwiw, some fixes are required, I got build failures against PG12. (Log not at hand at the moment, sorry.)

**Comment by jfinzel** [comment]
@df7cb yes, we have this planned to work on in an upcoming sprint.  It should not be too long. 
 Thanks.

**Comment by cpaelzer** [comment]
Hi,
in case the sprint was planned to be in person we all know that these tend to be cancelled recently :-/
Any updates or an ETA on this would be great to know about (get it back into Ubuntu where it was removed along postgresql-11).

**Comment by jfinzel** [comment]
@cpaelzer @df7cb it's still planned, yes.  Look for a release **at the latest** within 2 weeks.

**Comment by jfinzel** [comment]
@df7cb everything should be good to go now with https://github.com/enova/pgl_ddl_deploy/releases/tag/v1.7.0.  I have a question if you could help me with it.  My colleague @chicagomikee could not get the build to run, though it ran fine for me.  Here are his logs:
```
$ debuild -us -uc --lintian-opts --profile debian
 dpkg-buildpackage -rfakeroot -D -us -uc
dpkg-buildpackage: source package pgl-ddl-deploy
dpkg-buildpackage: source version 1.7.0-1
dpkg-buildpackage: source distribution unstable
dpkg-buildpackage: source changed by Michael Elterman <melterman@enova.com>
 dpkg-source --before-build pgl_ddl_deploy
dpkg-buildpackage: host architecture amd64
 fakeroot debian/rules clean
pg_buildext checkcontrol
--- debian/control	2020-03-17 11:40:33.482843365 -0500
+++ debian/control.hQrDkv	2020-03-17 11:41:14.396145848 -0500
@@ -13,3 +13,27 @@
 Depends: postgresql-9.5, postgresql-9.5-pglogical, ${shlibs:Depends}, ${misc:Depends}
 Description: Transparent DDL replication for PostgreSQL
  Automated DDL deployment using PgLogical for PostgreSQL 9.5.
+
+Package: postgresql-9.6-pgl-ddl-deploy
+Architecture: any
+Depends: postgresql-9.6, postgresql-9.6-pglogical, ${shlibs:Depends}, ${misc:Depends}
+Description: Transparent DDL replication for PostgreSQL
+ Automated DDL deployment using PgLogical for PostgreSQL 9.6.
+
+Package: postgresql-10-pgl-ddl-deploy
+Architecture: any
+Depends: postgresql-10, postgresql-10-pglogical, ${shlibs:Depends}, ${misc:Depends}
+Description: Transparent DDL replication for PostgreSQL
+ Automated DDL deployment using PgLogical for PostgreSQL 10.
+
+Package: postgresql-11-pgl-ddl-deploy
+Architecture: any
+Depends: postgresql-11, postgresql-11-pglogical, ${shlibs:Depends}, ${misc:Depends}
+Description: Transparent DDL replication for PostgreSQL
+ Automated DDL deployment using PgLogical for PostgreSQL 11.
+
+Package: postgresql-12-pgl-ddl-deploy
+Architecture: any
+Depends: postgresql-12, postgresql-12-pglogical, ${shlibs:Depends}, ${misc:Depends}
+Description: Transparent DDL replication for PostgreSQL
+ Automated DDL deployment using PgLogical for PostgreSQL 12.
Error: debian/control needs updating from debian/control.in. Run 'pg_buildext updatecontrol'.
If you are seeing this message in a buildd log, a sourceful upload is required.
/usr/share/postgresql-common/pgxs_debian_control.mk:9: recipe for target 'debian/control' failed
make: *** [debian/control] Error 1
dpkg-buildpackage: error: fakeroot debian/rules clean gave error exit status 2
debuild: fatal error at line 1376:
dpkg-buildpackage -rfakeroot -D -us -uc failed
```

Thanks.

**Comment by df7cb** [comment]
Thanks for the new release, I've just uploaded the Debian packages.

Re: Jeremy Finzel 2020-03-17 <enova/pgl_ddl_deploy/issues/52/600188330@github.com>
> --- debian/control	2020-03-17 11:40:33.482843365 -0500
> +++ debian/control.hQrDkv	2020-03-17 11:41:14.396145848 -0500
> @@ -13,3 +13,27 @@
>  Depends: postgresql-9.5, postgresql-9.5-pglogical, ${shlibs:Depends}, ${misc:Depends}
>  Description: Transparent DDL replication for PostgreSQL
>   Automated DDL deployment using PgLogical for PostgreSQL 9.5.
> +
> +Package: postgresql-9.6-pgl-ddl-deploy
> +Architecture: any
[...]
> Error: debian/control needs updating from debian/control.in. Run 'pg_buildext updatecontrol'.

That means the two machines have a different
/etc/postgresql-common/supported_versions file, from Debian/Ubuntu
(where it targets one version) vs from apt.postgresql.org (where it
targets all "supported" versions). This file is used by
/usr/share/postgresql-common/supported-versions to do the actual work.

What variant is actually stored in git doesn't matter much, I'm
regenerating the debian/control file from debian/control.in anyway.

To fix, run the mentioned `pg_buildext updatecontrol` command or set
`PG_UPDATECONTROL=yes` in the environment.

Christoph

**Comment by jfinzel** [comment]
Resolved with https://github.com/enova/pgl_ddl_deploy/pull/53

**Comment by cpaelzer** [comment]
BTW thank you @jfinzel !
