### ISSUE TITLE
Native driver - table not added to publication

### ISSUE THREAD

**Issue by dfillingham** [enova/pgl_ddl_deploy#64]
Hi there,

Is my understanding correct that when using the native driver and `include_schema_regex`, that any tables created within that schema will get auto-added to the publication?

Having an issue where I've installed and configured the extension and the DDL is replicating to the subscriber, but the table isn't being auto-added to the publication.

I ran the suggested debug query from the docs:
```
SELECT sc.set_name, n.nspname
FROM pg_namespace n
INNER JOIN pgl_ddl_deploy.set_configs sc
  ON nspname !~* pgl_ddl_deploy.exclude_regex()
  AND n.nspname ~* sc.include_schema_regex
ORDER BY sc.set_name, n.nspname;
```
which correctly gave me:
```
      set_name      |   nspname
--------------------+--------------
 prod2              | myschema
```

If I create a table on the provider and populate rows ie:
```
create table myschema.test1 (name text);
insert into myschema.test1 (name) values ('david');
```

I can then see the table gets created on the subscriber, but no data is sent:
```
select * from myschema.test1;
 name
------
(0 rows)
```

On the provider, it seems that the table isn't added to the publication:
```
select * from pg_publication_tables where tablename = 'mytest';
 pubname | schemaname | tablename
---------+------------+-----------
(0 rows)
```

Any ideas?

**Comment by jfinzel** [comment]
@dfillingham your understanding is correct.  We will investigate this hopefully this week.  Thanks!

**Comment by dfillingham** [comment]
Whoops, it even says so right in the postgres docs.

Yes with a primary key it's working correctly, thanks for the help :)
