### ISSUE TITLE
New table added to publication, created on replica, but somehow *not* subscribed?

### ISSUE THREAD

**Issue by depesz** [enova/pgl_ddl_deploy#68]
I have a case where we added new table to schema that is being replicated, and watched over by pgl_ddl_deploy.

Table was properly "discovered" on source, added to publication, and got created on replica, but it's not "subscribed".

Am I missing something, did something didn't work right, or is it a bug?

Not sure how to provide more information aside from:

On source:

```
=# select * from pg_publication_tables  where schemaname = 'cluster328' and tablename = 'auditor_feature_flag_records_2022_8';
  pubname  │ schemaname │              tablename              
═══════════╪════════════╪═════════════════════════════════════
 focal14_1 │ cluster328 │ auditor_feature_flag_records_2022_8
(1 row)
```

On replica:

```
=# \d cluster328.auditor_feature_flag_records_2022_8
                                           Table "cluster328.auditor_feature_flag_records_2022_8"
     Column      │            Type             │ Collation │ Nullable │                               Default                               
─────────────────┼─────────────────────────────┼───────────┼──────────┼─────────────────────────────────────────────────────────────────────
 id              │ bigint                      │           │ not null │ nextval('cluster328.auditor_feature_flag_records_id_seq'::regclass)
...
Indexes:
    "auditor_feature_flag_records_2022_8_pkey" PRIMARY KEY, btree (id), tablespace "data1"
...

=# select * from pg_subscription_rel where srrelid = 'cluster328.auditor_feature_flag_records_2022_8'::regclass;
 srsubid │ srrelid │ srsubstate │ srsublsn 
─────────┼─────────┼────────────┼──────────
(0 rows)
```

One bit of information that might be related, is that this table inherits other table that is properly pub/subbed.

We use inheritance as a way to parittion, as the app was migrated from very old pg, and we didn't (yet) get to properly re-parittion everything to native partitioning.

Anything I can provide to help you help me?

**Comment by jfinzel** [comment]
@depesz please forgive the long overdue reply to your issue!  First of all, can you confirm as noted in the README that you manually ran ALTER SUBSCRIPTION ... REFRESH PUBLICATION?

> NOTE - after creating a table using schema-regex-based DDL replication with native logical replication, it is necessary to manually execute on the subscriber the command SELECT pgl_ddl_deploy.retry_all_subscriber_logs(); to complete the process of adding the new table to replication. This is because of the bug https://www.postgresql.org/message-id/CAMa1XUh7ZVnBzORqjJKYOv4_pDSDUCvELRbkF0VtW7pvDW9rZw@mail.gmail.com preventing the safety of running ALTER SUBSCRIPTION ... REFRESH PUBLICATION in a replication process. This will be updated as soon as a patch becomes available.

If you already tried this, then can you show me the contents of these two tables:
 - `pgl_ddl_deploy.events`
 - `pgl_ddl_deploy.set_configs` - at least the row that controls this schema'

Thank you.

**Comment by depesz** [comment]
Well, I can't do tests now. I *think*/remember that doing refresh helped. The problem is that we found more problems with logical replication, and missing wals, reported it to pgsql-bugs, but for now no fixes are there, so the upgrade project got stopped.
I think we can close this issue, if I will go back to the upgrade, and will see any problems, will let you know.
